-- MTW: bashing areas table

mtw.attacks = {
--Fighting
atk_trip = {def = "block", class = "", aff = "prone", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_sever = {def = "block", class = "", aff = "", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_decapitate = {def = "block", class = "", aff = "", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Soldier: Arms
atk_slash = {def = "parry", class = "soldier", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_club = {def = "parry", parry = "soldier", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_obliterate = {def = "dodge", class = "soldier", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_threaten = {def = "", class = "soldier", aff = "", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_wildstrike = {def = "parry", class = "soldier", aff = "reckless", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_sunder_armor = {def = "jump", class = "soldier", aff = "sundered armor", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_grab = {def = "block", class = "soldier", aff = "grabbed", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_evict
atk_heartstrike = {def = "duck", class = "soldier", aff = "adrenaline", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_throwdown = {def = "none", class = "soldier", aff = "prone", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_cleave = {def = "duck", class = "soldier", aff = "blurry_vision", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_headslam = {def = "none", class = "soldier", aff = "equilloss", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_counter = {def = "", class = "soldier", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_shield_smash = {def = "dodge", class = "soldier", aff = "stun", getting_hit = false, attacker = "none", defend_now = false, delay = 2, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_mutilating_hack = {def = "block", class = "soldier", aff = "cut_tendon", aff_def = "cut_tendon" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_impale = {def = "dodge", class = "soldier", aff = "impaled", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_bind = {def = "block", class = "soldier", aff = "equilloss", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_batter = {def = "duck", class = "soldier", aff = "battered", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_assault = {def = "parry", class = "soldier", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_rupture = {def = "jump", class = "soldier", aff = "bleeding", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_rend = {def = "", class = "soldier", aff = "bleeding", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_enervating_jab = {def = "dodge", class = "soldier", aff = "exhaustion", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_enfeeble = {def = "duck", class = "soldier", aff = "infirm", aff_def = "infirm" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_terminate = {def = "none", class = "soldier", aff = "death", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Soldier: Warcraft
--atk_intercept
--atk_surging_smash = {def = "", class = "soldier", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_desperate_strike = {def = "jump", class = "soldier", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_charge
--Soldier: Brutality
atk_rake = {def = "parry", class = "soldier", aff = "bleeding", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_roar_maddening = {def = "instant", class = "soldier", aff = "confusion", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_gutsmash = {def = "block", class = "soldier", aff = "ataxia OR anemia OR vomiting", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_blackeye = {def = "jump", class = "soldier", aff = "blackout", aff_def = "blind" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_slit_throat = {def = "jump", class = "soldier", aff = "slitthroat", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_legslice = {def = "duck", class = "soldier", aff = "severed_tendon", aff_def = "hamstring" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_nerve_strike = {def = "parry", class = "soldier", aff = "cataplexy", aff_def = "dystonia" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_crunch_arms = {def = "duck", class = "soldier", aff = "maladroitness", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_roar_mighty = {def = "block", class = "soldier", aff = "clumsiness", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_headsmash = {def = "dodge", class = "soldier", aff = "headache", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_shatter_left_leg = {def = "parry", class = "soldier", aff = "broken_left_leg", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_shatter_right_leg = {def = "parry", class = "soldier", aff = "broken_right_leg", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_shatter_left_arm = {def = "parry", class = "soldier", aff = "broken_left_arm", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_shatter_right_arm = {def = "parry", class = "soldier", aff = "broken_right_arm", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_knockdown = {def = "dodge", class = "soldier", aff = "prone", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_earbash = {def = "earbash", class = "soldier", aff = "deaf", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_burst_lungs = {def = "duck", class = "soldier", aff = "asthma", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_crush_skull = {def = "block", class = "soldier", aff = "brain_damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_roar_deafening = {def = "block", class = "soldier", aff = "sensitivity", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_brainbash = {def = "duck", class = "soldier", aff = "dizzy OR impatient OR concussion", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_chestbash = {def = "block", class = "soldier", aff = "heart_palpitations", aff_def = "collapsed_lung" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_roar_terrifying = {def = "block", class = "soldier", aff = "terror", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_stomp = {def = "", class = "soldier", aff = "random", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_pulverize = {def = "block", class = "soldier", aff = "cataplexy", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_burst_organs = {def = "duck", class = "soldier", aff = "burst_organs", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_roar_dreadful = {def = "block", class = "soldier", aff = "tainted_aura", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Soldier: Swordmastery
atk_starfury = {def = "parry", class = "soldier", aff = "arcane_fire", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_wisplight = {def = "instant", class = "soldier", aff = "impatient OR headache", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_hummingbird = {def = "dodge", class = "soldier", aff = "weak_legs", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_icehowl = {def = "dodge", class = "soldier", aff = "chilled", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_spinkick = {def = "block", class = "soldier", aff = "impatient", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_spinkick_slash = {def = "block", class = "soldier", aff = "bleeding impatient", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_lunarburst = {def = "instant", class = "soldier", aff = "depression OR confusion", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_windsong = {def = "block", class = "soldier", aff = "", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_thunderburst = {def = "instant", class = "soldier", aff = "balance loss", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_rainfall_arc = {def = "jump", class = "soldier", aff = "somnolence", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_leaf_breeze = {def = "jump", class = "soldier", aff = "concussion bleeding", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_mooncrescent = {def = "block", class = "soldier", aff = "burning_limb", aff_def = "burning_limb" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_whirlwind = {def = "parry", class = "soldier", aff = "bleeding", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_sunburst = {def = "instant", class = "soldier", aff = "epilepsy OR brain damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_cutting_clouds  = {def = "parry", class = "soldier", aff = "malaise confusion", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_thornrose = {def = "duck", class = "soldier", aff = "black_lung", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_phoenix_unfurls = {def = "none", class = "soldier", aff = "paralysis sensitivity", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_eclipse_over_water = {def = "none", class = "soldier", aff = "horror sun_allergy instability", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Rogue: Fencing
atk_thrust = {def = "dodge", class = "rogue", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_fleche = {def = "duck", class = "rogue", aff = "bleeding", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_hamstring = {def = "jump", class = "rogue", aff = "hamstrung", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_puncture = {def = "block", class = "rogue", aff = "defense_strip", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_wristflick = {def = "dodge", class = "rogue", aff = "clumsiness", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_lowblow = {def = "block", class = "rogue", aff = "weak_legs", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_backslice = {def = "block", class = "rogue", aff = "cut_tendon", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_hemorrhage = {def = "block", class = "rogue", aff = "anemia", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_beat = {def = "block", class = "rogue", aff = "equilloss", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_pommel = {def = "parry", class = "rogue", aff = "dizziness", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_balestra = {def = "parry", class = "rogue", aff = "severed_nerves", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_beguile = {def = "block", class = "rogue", aff = "disloyalty", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_flourish = {def = "parry", class = "rogue", aff = "interrupt", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_disarm = {def = "parry", class = "rogue", aff = "disarm", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_press = {def = "block", class = "rogue", aff = "press", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_glint = {def = "jump", class = "rogue", aff = "blind", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_inquartata = {def = "parry", class = "rogue", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_backhand = {def = "instant", class = "rogue", aff = "stun", getting_hit = false, attacker = "none", defend_now = false, delay = 0, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_coup_de_grace = {def = "none", class = "rogue", aff = "death", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Rogue: Subtlety
atk_backstab = {def = "none", class = "rogue", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_crossbow = {def = "duck", class = "rogue", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Rogue: Thievery
atk_hogtie = {def = "none", class = "rogue", aff = "entangled", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_vileblade = {def = "dodge", class = "rogue", aff = "guile_gain", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_slitthroat = {def = "jump", class = "rogue", aff = "bleeding", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_cheap_shot = {def = "duck", class = "rogue", aff = "vomiting", aff_def = "blackout" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_lungstab = {def = "dodge", class = "rogue", aff = "collapsed_lung", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_death_from_above = {def = "block", class = "rogue", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_shiv = {def = "dodge", class = "rogue", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_sucker_punch = {def = "block", class = "rogue", aff = "concussion", aff_def = "concussion" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_sleightofhand = {def = "jump", class = "rogue", aff = "random", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Rogue: Performance
atk_canto  = {def = "duck", class = "rogue", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_requiem = {def = "block", class = "rogue", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Magician: Thaumaturgy
atk_stormlance = {def = "duck", class = "magician", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_ignite = {def = "dodge", class = "magician", aff = "on_fire", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_chill = {def = "block", class = "magician", aff = "chilled", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_earthbind = {def = "dodge", class = "magician", aff = "earthbind", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_icespikes = {def = "dodge", class = "magician", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_earthquake = {def = "none", class = "magician", aff = "prone", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_static_discharge = {def = "parry", class = "magician", aff = "epileptic heart_palpitations", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_gale = {def = "duck", class = "magician", aff = "forced movement", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_skylash = {def = "parry", class = "magician", aff = "depressed", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_pyroclasm = {def = "???", class = "magician", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_keltonsknives = {def = "???", class = "magician", aff = "damage OR ataxia OR concussion OR on_fire OR ionized OR burns", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_shatter = {def = "dodge", class = "magician", aff = "broken_limb", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_tomb = {def = "???", class = "magician", aff = "stun", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_immolate = {def = "block", class = "magician", aff = "stun", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Magician: Arcana
atk_balefire = {def = "dodge", class = "magician", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_sleep = {def = "block", class = "magician", aff = "sleep", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_dementia = {def = "block", class = "magician", aff = "demented", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_counterspell = {def = "???", class = "magician", aff = "none", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_instability = {def = "duck", class = "magician", aff = "unstable", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_cripple = {def = "parry", class = "magician", aff = "crippled", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_barrage = {def = "instant", class = "magician", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_disorient = {def = "jump", class = "magician", aff = "disoriented", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_timeshift = {def = "block", class = "magician", aff = "malaise hypersomnia", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_compulsion = {def = "jump", class = "magician", aff = "compulsion", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_timequake = {def = "???", class = "magician", aff = "adrenaline_loss", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_astral_tether = {def = "Jump", class = "magician", aff = "tethered", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_teleport = {def = "???", class = "magician", aff = "", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_astral_warp = {def = "parry", class = "magician", aff = "warped", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_undoing = {def = "none", class = "magician", aff = "undoing", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Magician: Demonology
atk_scabies = {def = "block", class = "magician", aff = "scabies", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_howl_of_terror = {def = "duck", class = "magician", aff = "fear", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_curse_of_tongues = {def = "???", class = "magician", aff = "curse_of_tongues", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_seduce = {def = "parry", class = "magician", aff = "lust", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_necrotic_plague = {def = "duck", class = "magician", aff = "necrotic_plague", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_torture = {def = "duck", class = "magician", aff = "blackout", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Magician: Psionics
--Priest: Righteousness
atk_fury = {def = "duck", class = "priest", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_mandate = {def = "duck", class = "priest", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_heretic = {def = "duck", class = "priest", aff = "heretic", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_kneel = {def = "dodge", class = "priest", aff = "prone", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_atonement = {def = "block", class = "priest", aff = "atonement", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_spirit_wrack = {def = "dodge", class = "priest", aff = "random", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_holy_fire = {def = "parry", class = "damage", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_convocation = {def = "???", class = "priest", aff = "summon", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_wrathful_thunder = {def = "duck", class = "priest", aff = "balance loss", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_avenging_flame = {def = "dodge", class = "priest", aff = "black_lung", aff_def = "blind" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_divine_command = {def = "parry", class = "priest", aff = "commanded", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_retribution = {def = "dodge", class = "priest", aff = "retribution", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_righteous_lance = {def = "duck", class = "priest", aff = "broken_limb", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_searing_arc = {def = "jump", class = "priest", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_vindication = {def = "dodge", class = "priest", aff = "prone", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_indolent_penance
atk_holy_sword = {def = "parry", class = "priest", aff = "damage holy_shock", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_ill_omen = {def = "block", class = "priest", aff = "ill_omen ill_omen", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_divine_censure = {def = "block", class = "priest", aff = "censure", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_repentance = {def = "duck", class = "priest", aff = "repenting", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_damnation = {def = "block", class = "priest", aff = "damnation", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_reckoning = {def = "???", class = "priest", aff = "reckoning", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_judgment = {def = "none", class = "priest", aff = "death", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_sword_spirit = {def = "parry", class = "priest", aff = "withered befuddled", getting_hit = false, attacker = "none", defend_now = false, hitting_with = false, targeting = "none", time = createStopWatch()},
atk_verdict = {def = "instant", class = "priest", aff = "depression", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", time = createStopWatch()},
--Priest: Faith
atk_martyr = {def = "none", class = "priest", aff = "death", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Priest: Thanatology
atk_terror = {def = "dodge", class = "priest", aff = "terror", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_soulspear = {def = "dodge", class = "priest", aff = "reckless", aff_def = "dystonia", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_burden_soul = {def = "jump", class = "priest", aff = "weariness", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_withering_touch = {def = "block", class = "priest", aff = "dementia", aff_def = "cataplexy", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_exorcism = {def = "parry", class = "priest", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_gravechill = {def = "parry", class = "priest", aff = "chill", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_despair = {def = "parry", class = "priest", aff = "malaise", aff_def = "anemia" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_funeral_mass = {def = "jump", class = "priest", aff = "sensitivity", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_vision_of_death = {def = "parry", class = "priest", aff = "dizziness OR epilepsy OR fear", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_icy_grasp = {def = "parry", class = "priest", aff = "stun", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_entropy = {def = "jump", class = "priest", aff = "random", aff_def = "random", getting_hit = false, attacker = "none", defend_now = false, delay = 2, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_doom = {def = "???", class = "priest", aff = "death", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Priest: Pyromania
atk_pimmolate = {def = "parry", class = "priest", aff = "on_fire", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_illuminate = {def = "jump", class = "priest", aff = "", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_bloodboil = {def = "dodge", class = "priest", aff = "demention OR impatience OR blackout", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_melt = {def = "parry", class = "priest", aff = "defense_strip", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--atk_incinerate = {def = "???", class = "priest", aff = "death OR burns", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Priest: Shadoweaving
atk_torturous_whip = {def = "jump", class = "priest", aff = "maladroitness", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_shadow_theft = {def = "none", class = "priest", aff = "", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_grotesque_visage = {def = "dodge", class = "priest", aff = "stun OR paralysis", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_deceit = {def = "dodge", class = "priest", aff = "lust", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_horrify = {def = "duck", class = "priest", aff = "horror", getting_hit = false, attacker = "none", defend_now = false, delay = 2, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_shadowlance = {def = "none", class = "priest", aff = "", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_scarab_curse = {def = "jump", class = "priest", aff = "scabie hemophilia", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_shadow_storm = {def = "none", class = "priest", aff = "", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_oubliette = {def = "jump", class = "priest", aff = "", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Priest: Bloodlore
atk_savage = {def = "parry", class = "priest", aff = "bleeding", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_phlegm = {def = "parry", class = "priest", aff = "dizziness -paranoia-", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_mutilate = {def = "dodge", class = "priest", aff = "epilepsy", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_heart_thrum = {def = "jump", class = "priest", aff = "hemophilia", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_lunar_bay = {def = "jump", class = "priest", aff = "", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_gluttonous_lust = {def = "block", class = "priest", aff = "manaleech -mana loss-", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_sanguis = {def = "dodge", class = "priest", aff = "dystonia -sensitivity-", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_feral_rake = {def = "block", class = "priest", aff = "impatience", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_rending_strike = {def = "parry", class = "priest", aff = "severed_nerves -servered_nerves-", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_yellow_bile = {def = "block", class = "priest", aff = "maladroitness -recklessness-", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_sanguishift = {def = "none", class = "priest", aff = "bleeding", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_knife_of_woe = {def = "none", class = "priest", aff = "heart_palpitations", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_carnal_scream = {def = "none", class = "priest", aff = "concussion", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_black_bile = {def = "none", class = "priest", aff = "anemia -ataxia-", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_betrayal_of_blood = {def = "none", class = "priest", aff = "betrayed blood", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_forbidden_revel = {def = "none", class = "priest", aff = "death", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
--Priest: Crusading
atk_bold_smite = {def = "block", class = "priest", aff = "impatient", aff_def = "reckless" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_faithburn = {def = "instant", class = "priest", aff = "adrenaline", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_crushing_smite = {def = "dodge", class = "priest", aff = "concussion", aff_def = "brain_damage" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_dominating_strike = {def = "instant", class = "priest", aff = "damage", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_virtuous_smite = {def = "parry", class = "priest", aff = "epileptic", aff_def = "dizziness" , getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_coward = {def = "instant", class = "priest", aff = "shieldbreak stun retribution adrenaline", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
atk_revelation = {def = "jump", class = "priest", aff = "illumination", getting_hit = false, attacker = "none", defend_now = false, delay = 3, hitting_with = false, targeting = "none", timer = createStopWatch()},
}
